import { Button } from "@/common/components/button";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-5 text-center">
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
        <br />
        <Button primary={true} label="Button" />
      </main>
    </>
  );
}
